### ISSUE TITLE
Event Purchase Unit

### ISSUE THREAD

**Issue by DeaTh-ShiNoBi** [DeaTh-ShiNoBi/PrismataAssist#2]
I've decided how I think it will be best to handle events of purchasing units.  I believe that we a way to extract the cost of each individual unit.  This could be done with a Map that maps units to their cost.  I see this information being held within a simple file that our program would parse when it's ran, to populate the Map of unit costs.

However, rather than simply a cost of resources (i.e. Drone costs 3g and 1E), we can interpret the cost as "effect of purchasing that unit on the game state".  This effect can include more than just a change of resources.  For example, purchasing a Drone has an effect of -3g and -1E, but also has an additional effect of +1 NumDrones.  This can be kept track of in the "costs" of units (perhaps it's better to call it something other than cost here).  Doing so will allow us to have a single event for the purchase of any unit, ePurchaseUnit.  If that unit happens to have an effect on the rate of resource generation, that will be reflected in its effect on the game state.

The Map can map the hotkeys of base units to the effect of purchasing the unit on the game state, so "d" would map to -3g -1E +1 bNumDrones and "t" (Tarsier) would map to -4g.  Random set units would be mapped by a keyword that represents that unit, so "vivid" could represent Vivid Drone and be mapped to -2g -2E +1 bNumDrones.  The player will load random set units into numeric hotkeys at the start of the game, but our program can simply parse that hotkey as the keyword of the random set unit and feed that into the map.

We'll have to decide on how we want our file to be formatted.  It could be something like json or we could make our own format.

**Comment by mitchellwrosen** [comment]
The main disadvantage of interpreting a unit purchase as one monolithic function from old `GameState` to new `GameState` is you start to lose the nice composition of all of the smaller time-varying pieces of the game.

Taken to the extreme, we _could_ have just a `GameState` record and a single `bGameState :: Behavior GameState` that is not written as the applicative combination of the pieces of the game, but rather as its own `accumB` with a starting state and stepper event, like:

```haskell
bGameState :: Behavior GameState <-
  accumB initialGameState
    (unions
      [ ... ])
```

This `[ ... ]` list would then be massive, and would basically be the only event required to model the entire game. Unfortunately, each `Event` _within_ this list could not nicely sample whatever parts of the `GameState` it cares about - it would have to sample the entire `bGameState` behavior and then dig out the pieces it cares about. Certainly do-able, given this is in a recursive do-block, but it's not nice and compositional.

Our current architecture has the advantage that, when considering what some value is (like the current gold), there's only one place to look - the definition of `bGold`. We have a sort of "fan-in" style, where events (like `eUnitPurchased`) may be used in multiple different `Behavior` definitions (awkward; feels like you could do _everything_ that's supposed to occur when an event fires in one location), but each `Behavior` then gets to exist in isolation, which is nice and composable.

There is a middle-ground here somewhere, and it definitely depends on how the game actually works (like the fact that there are 100+ units seems to be a problem for the code today), but overall we should prefer having more smaller `Behavior`s to fewer big ones (I think).

Pure functions and data types would go a long way, too. For example, with our `Unit` type...

```haskell
data Unit = Drone | Conduit | Engineer | ...
```

we could have as many pure functions that we want, like:

```haskell
-- Price in gold
unitGoldCost :: Unit -> Gold

-- Price in energy
unitEnergyCost :: Unit -> Int

-- Number of drones generated
unitNumDrones :: Unit -> Int
```

`unitNumDrones` above might only return `1` for a `Drone` and `0` for everything else, but this would allow us to define `bNumDrones` in terms of `eUnitPurchased` directly:

```haskell
bNumDrones <- 
  accumB 6 
    (unions 
      [ (\unit drones -> unitNumDrones unit + drones) <@> eUnitPurchased
      , ...
      ])
```

So, lots of ways to go about designing this for sure, and we should reduce duplication/boilerplate as much as possible, but I'm not totally sure using a big pure function like

```haskell
unitPurchasedEffect :: Unit -> GameState -> GameState
```

is necessarily the right way (due to the detrimental effects it has on the structure of the network).

Worth a shot though!

**Comment by DeaTh-ShiNoBi** [comment]
I think we can still have multiple smaller behaviors without causing any problems.  However, I think we need to implement a way to requisition the cost of a unit in a way other than having an individual event for each unit.  Functions from Unit -> Gold and Unit -> NumDrones should work perfectly fine.  A big data type that knows every unit sounds like a good way to accomplish this goal.

A function like unitNumDrones is actually quite appropriate, I think.  It would be 1 for Drone and 0 for most units, true, but there are special drones like Wild Drone and Thorium Dynamo that generate more than 1 gold.
