### ISSUE TITLE
Undo last move/last turn

### ISSUE THREAD

**Issue by DeaTh-ShiNoBi** [DeaTh-ShiNoBi/PrismataAssist#3]
I want to implement a way to undo mistakes.  Something along the lines of backspace to undo the last move and 'u' or 'p' to undo the last turn.  In an imperative language, I would probably handle that with something along the lines of a list of lists (of gamestates, in the context of our program) where each element in the list of lists is a move that could be popped off and each whole list in the list of lists is a turn that could also be popped off.  However, this is a very side-effecting task (so it looks) and I'd like to know how we could do something like this in Haskell.

**Comment by mitchellwrosen** [comment]
Implementing undo-last-turn functionality might be tricky. Let's see...

We already have a time-varying game state and an event of next turns:

```haskell
bGameState :: Behavior GameState
eNextTurn :: Event ()
```

We need a time-varying last-game-state as well. There's not always a last turn to move to, so it seems like a `Behavior (Maybe GameState)`.

```haskell
bLastGameState :: Behavior (Maybe GameState)
```

We start with `Nothing`, and whenever `eNextTurn` fires, we can sample the current game state (the "old" game state just before it updates _as_ next turn is firing), and step to this value in our `bLastGameState`:

We also want undoing a turn to reset the `bLastGameState` to `Nothing`, because you can't undo twice in a row.

And now the tricky part: we need to incorporate `bLastGameState` into the definition of `bGameState` itself! Currently `bGameState` is just a composition of `Behavior`s, so that'll have to change.

Once we do all that, extending undo functionality to individual purchases/actions, and also allowing multiple undos in a row, should be more straightforward.

**Comment by mitchellwrosen** [comment]
I discovered what the problem with our undo functionality was. In reactive-banana, there's no way for a behavior to be updated from "afar" (this is a big benefit of FRP style).

We were trying to effectively reset all of the behaviors `bGold`, `bNumDrones`, etc. when the undo button was pressed, but we ended up doing something else - just switching away the vacuous "summary" behavior `bGameState`.

So when you press `ddud`, it appears that the last `d` does nothing, because you are sitting at 0 gold (though the screen indicates you are at 6, per the vacuous veneer `GameState` that was switched to).

One (bad, but straightforward) solution: include in the definition of all relevant behaviors the `eUndoTurn` event. It's the straightforward FRP Way™. This would work, but would require additional bookkeeping for every single behavior in our game state, since we would need to know what value to return to.

Another solution that comes to mind is to use a bit of tricky higher-order FRP to essentially "restart" the game with the latest `GameState`.

Here's how that would work:

Conceptually, our entire network is defined at a single moment in time. This is the `Moment` abstraction. A `Moment a` represents an `a` that exists at a specific time (or, equivalently, _every_ moment in time, quite like a `Behavior`, since the computation itself is not certain exactly _when_ it will be run, just that when it does run, it will be "told" the time).

There is a combinator that makes good use of this concept:

```haskell
observeE :: Event (Moment a) -> Event a
```

This says, given an `Event` of computations that, when "told" what the current time is, compute an `a`, return an `Event` of the `a` computed at exactly the times the original `Event` emitted! (Confused yet?)

Another way of putting it: 

- The semantic meaning of `Event a` is `[(a, Time)]` (a list of `a` that each occur at a specific moment in time)
- The semantic meaning of `Moment a` is `Time -> a` (an `a` that is dependent upon what time it is).

Therefore, an `Event (Moment a)` is semantically `[(Time -> a, Time)]`. Looking at each occurrence `(Time -> a, Time)`, we have the computation that is dependent upon what time it is, and the current time that it is being emitted. We can provide this current time to the function to compute our `a`.

**Comment by mitchellwrosen** [comment]
Now returning to the definition of the entire network:

```haskell
Event Char -> Moment (Behavior GameState)
```

Given our input event, we compute a time-varying `GameState`, dependent upon the current time. (The outer machinery that runs the network of course passes "the beginning of time" as the time we are computed).

I'm thinking we can modify this slightly to include the `GameState` to use at the beginning of time.

```haskell
Event Char -> GameState -> Moment (Behavior GameState)
```

Now the higher-order tricky bits:

Say we still have the following.

```haskell
eUndoTurn :: Event ()
bLastGameState :: Behavior GameState
```

When `eUndoTurn` fires, we want to sample the `GameState` to switch to, carried by `bLastGameState`. Simple enough so far...

```haskell
let eLastGameState :: Event GameState 
    eLastGameState = bLastGameState <@ eUndoTurn :: Event GameState
```

We want to use this `GameState` as _input_ to _the network definition_, which (again) is dependent upon the moment it is run (it's in the `Moment` monad). Behold:

```haskell
let eNextPrismataAssist :: Event (Moment (Behavior GameState))
    eNextPrismataAssist = prismataAssist eInput <$> eLastGameState
```

Shrinking the `Event (Moment a)` to `Event a` with `observeE`, we end up with an `Event (Behavior GameState)` suitable for switching to with `switchB`.

Because this new `Event (Behavior GameState)` actually switches to a whole new network, we don't accidentally stop referring to `bGold` and such, which was the original bug. We create the entire network anew with a new initial `GameState` - namely, the one we kept around in a `Behavior` in case the undo-turn action was taken.

**Comment by mitchellwrosen** [comment]
I'm not sure if this would work, I've never tried it. There is possibly a much simpler solution out there, but it does seem like having a bunch of locally-stateful, time-varying, composable pieces of a game is in direct conflict with an authoritative "god command" that resets everything, as an undo-turn action would. That's more-or-less the imperative, callback-style architecture for event handling. Very tricky problem, I'll think about it some more for sure.

**Comment by mitchellwrosen** [comment]
Another option: invert the dependency relationship between `GameState` and its parts (as you originally suggested in issue #2).

We'd then have (ignoring switching/undo for a second):

```haskell
bGameState :: Behavior GameState <-
  accumB game0
    (unions
      [ ... ])

-- If we want them, these are available
let bGold = gameGold <$> bGameState
let bNumDrones = gameNumDrones <$> bGameState
... etc ...
```

Then, the `bGameState` really is authoritative (not derived from other behaviors), so switching it directly (as our code does right now) would be fine. Maybe that's the right way to solve this.
